import {resolveSync} from '@reskript/core/willBreakingInternalUseOnly';
import lessSyntax from 'postcss-less';

const config: Record<string, any> = {
    plugins: [
        resolveSync('stylelint-stylistic'),
    ],
    // 由于[Stylelint不再支持风格型的规则](https://stylelint.io/migration-guide/to-15)，
    // 我们暂时无法直接使用`@ecomfe/stylelint-config`的配置，因此复制一份规则
    rules: {
        'stylistic/at-rule-name-case': 'lower',
        'stylistic/at-rule-name-space-after': 'always-single-line',
        'stylistic/at-rule-semicolon-newline-after': 'always',
        'stylistic/block-closing-brace-empty-line-before': 'never',
        'stylistic/block-closing-brace-newline-after': 'always',
        'stylistic/block-closing-brace-newline-before': 'always-multi-line',
        'stylistic/block-closing-brace-space-before': 'always-single-line',
        'stylistic/block-opening-brace-newline-after': 'always-multi-line',
        'stylistic/block-opening-brace-space-after': 'always-single-line',
        'stylistic/block-opening-brace-space-before': 'always',
        'stylistic/color-hex-case': 'lower',
        'stylistic/declaration-bang-space-after': 'never',
        'stylistic/declaration-bang-space-before': 'always',
        'stylistic/declaration-block-semicolon-newline-after': 'always-multi-line',
        'stylistic/declaration-block-semicolon-space-after': 'always-single-line',
        'stylistic/declaration-block-semicolon-space-before': 'never',
        'stylistic/declaration-block-trailing-semicolon': 'always',
        'stylistic/declaration-colon-newline-after': 'always-multi-line',
        'stylistic/declaration-colon-space-after': 'always-single-line',
        'stylistic/declaration-colon-space-before': 'never',
        'stylistic/function-comma-newline-after': 'always-multi-line',
        'stylistic/function-comma-space-after': 'always-single-line',
        'stylistic/function-comma-space-before': 'never',
        'stylistic/function-max-empty-lines': 0,
        'stylistic/function-parentheses-newline-inside': 'always-multi-line',
        'stylistic/function-parentheses-space-inside': 'never-single-line',
        'stylistic/function-whitespace-after': 'always',
        'stylistic/indentation': 4,
        'stylistic/max-empty-lines': 1,
        'stylistic/media-feature-colon-space-after': 'always',
        'stylistic/media-feature-colon-space-before': 'never',
        'stylistic/media-feature-name-case': 'lower',
        'stylistic/media-feature-parentheses-space-inside': 'never',
        'stylistic/media-feature-range-operator-space-after': 'always',
        'stylistic/media-feature-range-operator-space-before': 'always',
        'stylistic/media-query-list-comma-newline-after': 'always-multi-line',
        'stylistic/media-query-list-comma-space-after': 'always-single-line',
        'stylistic/media-query-list-comma-space-before': 'never',
        'stylistic/no-eol-whitespace': true,
        'stylistic/no-missing-end-of-source-newline': true,
        'stylistic/number-leading-zero': 'never',
        'stylistic/number-no-trailing-zeros': true,
        'stylistic/property-case': 'lower',
        'stylistic/selector-attribute-brackets-space-inside': 'never',
        'stylistic/selector-attribute-operator-space-after': 'never',
        'stylistic/selector-attribute-operator-space-before': 'never',
        'stylistic/selector-combinator-space-after': 'always',
        'stylistic/selector-combinator-space-before': 'always',
        'stylistic/selector-descendant-combinator-no-non-space': true,
        'stylistic/selector-list-comma-newline-after': 'always',
        'stylistic/selector-list-comma-space-before': 'never',
        'stylistic/selector-max-empty-lines': 0,
        'stylistic/selector-pseudo-class-case': 'lower',
        'stylistic/selector-pseudo-class-parentheses-space-inside': 'never',
        'stylistic/selector-pseudo-element-case': 'lower',
        'selector-pseudo-element-colon-notation': 'double',
        'selector-type-case': 'lower',
        'stylistic/unit-case': 'lower',
        'stylistic/value-list-comma-newline-after': 'always-multi-line',
        'stylistic/value-list-comma-space-after': 'always-single-line',
        'stylistic/value-list-comma-space-before': 'never',
        'stylistic/value-list-max-empty-lines': 0,
        'stylistic/no-extra-semicolons': true,
        'at-rule-empty-line-before': [
            'always',
            {
                except: ['blockless-after-same-name-blockless', 'first-nested'],
                ignore: ['after-comment'],
            },
        ],
        'color-hex-length': 'short',
        'comment-empty-line-before': [
            'always',
            {
                except: ['first-nested'],
                ignore: ['stylelint-commands'],
            },
        ],
        'comment-whitespace-inside': 'always',
        'custom-property-empty-line-before': [
            'always',
            {
                except: ['after-custom-property', 'first-nested'],
                ignore: ['after-comment', 'inside-single-line-block'],
            },
        ],
        'declaration-block-single-line-max-declarations': 1,
        'declaration-empty-line-before': [
            'always',
            {
                except: ['after-declaration', 'first-nested'],
                ignore: ['after-comment', 'inside-single-line-block'],
            },
        ],
        'function-name-case': 'lower',
        'length-zero-no-unit': true,
        'rule-empty-line-before': [
            'always-multi-line',
            {
                except: ['first-nested'],
                ignore: ['after-comment'],
            },
        ],
        'at-rule-no-unknown': [
            true,
            {
                ignoreAtRules: [
                    'tailwind',
                ],
            },
        ],
        'block-no-empty': true,
        'color-no-invalid-hex': true,
        'comment-no-empty': true,
        'declaration-block-no-duplicate-properties': [
            true,
            {
                ignore: ['consecutive-duplicates-with-different-values'],
            },
        ],
        'declaration-block-no-shorthand-property-overrides': true,
        'font-family-no-duplicate-names': true,
        'function-calc-no-unspaced-operator': true,
        'function-linear-gradient-no-nonstandard-direction': true,
        'keyframe-declaration-no-important': true,
        'media-feature-name-no-unknown': true,
        'no-duplicate-at-import-rules': true,
        'no-duplicate-selectors': true,
        'no-empty-source': true,
        'no-invalid-double-slash-comments': true,
        'property-no-unknown': [
            true,
            {
                ignoreProperties: ['composes'],
            },
        ],
        'selector-pseudo-class-no-unknown': [
            true,
            {
                ignorePseudoClasses: ['global'],
            },
        ],
        'selector-pseudo-element-no-unknown': true,
        'selector-type-no-unknown': true,
        'string-no-newline': true,
        'unit-no-unknown': true,
    },
    overrides: [
        {
            files: ['**/*.less'],
            customSyntax: lessSyntax,
        },
    ],
};

export default config;
