name: NodeJS CI

on:
  push:
    branches: [master, v*-**]
  pull_request:
    branches: [master, v*-**]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.x
    - uses: actions/checkout@v2
    - name: Setup Node 16
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: pnpm install
    - run: pnpm run build
    - run: pnpm run lint
    - run: pnpm run test
      env:
        CI: true
    - name: Setup NodeJS 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Unit Test NodeJS 14
      run: pnpm run test
      env:
        CI: true
