name: NodeJS 16 CI

on:
  push:
    branches: [master, v*-**]
  pull_request:
    branches: [master, v*-**]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.x
    - uses: actions/checkout@v2
    - name: Setup Node 16
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install Dependency
      run: pnpm install
    - name: Build
      run: pnpm run build
    - name: Lint
      run: pnpm run lint
    - name: Install Playwright
      working-directory: showcase/todo
      run: npx playwright install-deps chromium && npx playwright install chromium
    - name: Test
      run: pnpm run test
      env:
        CI: true
